### ISSUE TITLE
Player not found

### ISSUE THREAD

**Issue by Yaryujin** [downthecrop/wegame-tencent-china-opgg#2]
I searched for the top player "斗鱼丶鱼玄机" of the chinese super server (area id 31) and it said player not found, i tried a few other such as the ones from your blog and it still said player not found

**Comment by downthecrop** [comment]
name searching endpoint was moved somewhere else so I'd need to reverse the new endpoint. I was expecting to be playing on CN in 2020/2021 but with current global circumstances this project is on indefinite hiatus 
![cmd_mm1QZbG27q](https://user-images.githubusercontent.com/4764745/117331220-64b07c00-ae4b-11eb-9a10-c7f56d29c307.png)
