### ISSUE TITLE
Can't use it

### ISSUE THREAD

**Issue by Grecbg** [downthecrop/wegame-tencent-china-opgg#3]
Hey, I just installed the chrome app but it's not working and showing me this error  : https://i.imgur.com/XMFjqzs.png
Thanks in advance

**Comment by BakaFT** [comment]
Same.
Change line 209 to:
`        let topbar = document.getElementsByClassName("wgnav")[0];`
Then if it's not showing error but still can't see a button, it may be a 0px*0px size button, I dont know about the CSS.
But you could just execute this in console:
`document.getElementById("myModal").style.display = "block"`
and the App DOM should be showing now.

You will know what I'm doing  if you know basic HTML and  Javascript DOM Operations.

**Comment by BakaFT** [comment]
Since this repo hasn't updated for a long time and wegame.com.cn has changed a little bit, so you need to do some modifications to adapt to the changes.
The fix I commented above is not that good but can make this app works anyway.

**Comment by BakaFT** [comment]
A easy fix for that, which will directly show this app when after login:
https://github.com/BakaFT/wegame-tencent-china-opgg/commit/bd562d4f2513c9bf73bb2551c003793e8cb069a6
or You can copy and paste to overwrite your `script.js` with:
https://raw.githubusercontent.com/BakaFT/wegame-tencent-china-opgg/bd562d4f2513c9bf73bb2551c003793e8cb069a6/Extension/script.js

**Comment by downthecrop** [comment]
https://github.com/downthecrop/wegame-tencent-china-opgg/issues/5
