### ISSUE TITLE
Uncaught TypeError: Cannot read property 'appendChild' of undefined

### ISSUE THREAD

**Issue by suka233** [downthecrop/wegame-tencent-china-opgg#4]
Uncaught TypeError: Cannot read property 'appendChild' of undefined

https://www.wegame.com.cn/

script.js:302 (匿名函数)

![image](https://user-images.githubusercontent.com/43712875/128624650-1816e0d4-e81c-4803-9cda-213b52a33343.png)

**Comment by downthecrop** [comment]
https://github.com/downthecrop/wegame-tencent-china-opgg/issues/5
