### ISSUE TITLE
Project Status -  Read Me

### ISSUE THREAD

**Issue by downthecrop** [downthecrop/wegame-tencent-china-opgg#5]
Currently this project will not work without considerable retooling. The API endpoints have changed and the WeGame website has been redesigned which breaks my GUI injection from the extension. 

Before ![68747470733a2f2f692e696d6775722e636f6d2f745862423568452e706e67](https://user-images.githubusercontent.com/4764745/128662428-b95fc164-bcd0-435c-8850-dfdc7c4cdb5d.png)

After: 
![128624650-1816e0d4-e81c-4803-9cda-213b52a33343](https://user-images.githubusercontent.com/4764745/128662471-b7ac772f-af47-424e-82cd-12b108d2fe17.png)

Due to the nature of this using undocumented private API calls it breaks often. Without someone actively maintaining the codebase with small fixes it will fall out of date. 

https://github.com/downthecrop/wegame-tencent-china-opgg/issues/2

I created this as a quality of life tool for myself as I expected to be traveling and playing on WeGame servers. Until that happens I will not be providing support or updates for this.

HOWEVER if you want to fix the API calls and UI please make a pull request 😘

**Comment by wwhywy** [comment]
能谈合作？我需要用到，费用你这边说下

**Comment by downthecrop** [comment]
Excellent news for all my friends in China. IT STILL WORKS!

![](https://i.imgur.com/fmT5eJO.png)

Updates coming soon.

**Comment by downthecrop** [comment]
Project is operational again.

https://github.com/downthecrop/wegame-tencent-china-opgg/commit/68532b0c96972a842513c853c00becc936190c8d
